### ISSUE TITLE
Request with JSON Content-Type

### ISSUE THREAD

**Issue by spartan** [zendframework/zend-diactoros#287] opened 2018-01-16 18:45 UTC
I believe in the case below the `getParsedBody` should return an array. Currently returns `NULL`.

```php
$request = $request
        ->withHeader('Content-Type', 'application/json')
        ->withBody(new StringStream('{"message":"Ok"}');

 // returns null - should return array
$request->getParsedBody();

// returns json string
(string)$request->getBody();
```

**Comment by froschdesign** [comment] 2018-01-16 19:48
I think this is a duplicate of #278

**Comment by weierophinney** [comment] 2018-01-16 20:10
Parsing the body contents is out of scope for the `ServerRequest` class.

The reason is that _how_ to parse the body will vary based on the request content type. x-www-form-urlencoded is different from JSON is different from XML, and within XML, how that gets parsed will be highly dependent on the XML schema and how it relates to domain objects.

On top of that, even with JSON, how it is parsed will often be up to the specific application. Some will want JSON objects mapped to `stdClass` instances, while others (like yourself) will want associative arrays.

As such, it's up to the application to determine how to parse the body. This is a job generally left to middleware.

**Closed by weierophinney** 2018-01-16 20:10 UTC

**Comment by spartan** [comment] 2018-01-16 20:58
@weierophinney 
Indeed it makes more sense to handle it in the middleware. Thank you.
